sudo: required
services: 
  - docker

before_install: 
  - docker build -t colteks01/docker-react -f Dockerfile.dev . 

script: 
  - docker run colteks01/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react01" #app name you used
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-684268413554" #check s3 in aws and match time, region and app to S3
  bucket_path: "docker-react01" #same as app name for first deployment 
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

